version: "3"

services:
    server:
        image: klakegg/hugo:0.85.0-ext-ubuntu-onbuild
        container_name: hugo-server
        # command: new site /src
        command: server
        volumes:
        - "./:/src"
        ports:
        - "1313:1313"